root=
{
	items=
	{
        {
            cmd="COMMAND_CREATE_NODE",
            nodeClass="Boundary",
            status=
            {
                statusCode="STATUS_OK",
                nodeID=0,
            },
            assertions=
            {
                {
                    path="graph.numNodes",
                    value=1,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
                {
					path="graph.numPorts",
					value=0,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
                },
            },
        },
        {
			cmd="COMMAND_ADD_PORT",
			node=0,
			name="test",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_PORT_ID",
				portID=0,
			},
			value=
			{
				typeIndex="TYPE_VALUE",
				value=1.0,
			},
			assertions=
			{
				{
					path="graph.numPorts",
					value=1,
				},
			},
			existing=
			{
				{
					class="Port",
					properties=
					{
						name="test",
						value=
						{
							typeIndex="TYPE_VALUE",
							value=1.0,
						},
					},
				},
			},
        },
	}
}
