root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="MathsNode",
			nodeName="m1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
 				nodeID=0,
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="MathsNode",
			nodeName="m2",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
 				nodeID=1,
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=2,
			toPort=3,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
				signalPathID=0,
			},
			assertions=
			{
			},
		},
		{
			cmd="COMMAND_SELECT",
			selection=
			{
				0,
				1,
			},
			selectionMode="SELECTION_SET",
			assertions=
			{
				{
					path="numSelectedNodes",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_COPY_NODE",
			status=
			{
				statusCode="STATUS_OK",
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=4,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.numPorts",
					value=12,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.numSignalPaths",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			}
		},
		{
			cmd="COMMAND_COMPARE_NODES",
			status=
			{
				statusCode="STATUS_OK",
			},
			assertions=
			{
			},
		},
	},
}
