root=
{
	items=
	{
        {
            cmd="COMMAND_CREATE_NODE",
            nodeClass="GroupTyped",
            status=
            {
                statusCode="STATUS_OK",
                nodeID=0,
            },
            assertions=
            {
                {
                    path="graph.numNodes",
                    value=1,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
                {
					path="graph.numPorts",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
                },
            },
        },
        {
			cmd="COMMAND_SET_NODE_ACTIVE",
			node=0,
			commented="ACTIVE_OFF",
			existing=
			{
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=0,
				},
                {
					path="graph.numPorts",
					value=0,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
                },
			},
        },
        {
			cmd="COMMAND_SET_NODE_ACTIVE",
			node=0,
			commented="ACTIVE_PASS_THROUGH",
			existing=
			{
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=1,
				},
                {
					path="graph.numPorts",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
                },
			},
        },
        {
			cmd="COMMAND_SET_NODE_ACTIVE",
			node=0,
			commented="ACTIVE_ON",
			existing=
			{
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=1,
				},
                {
					path="graph.numPorts",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
                },
			},
        },
	}
}
