root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=0,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="FooTyped",
			nodeName="foo1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=1,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=0,
			toPort=2,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
				signalPathID=0,
			},
			assertions=
			{
				{
					path="graph.ports[0].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.ports[2].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
                {
                    path="graph.numSignalPaths",
                    value=1,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
			},
		},
        {
            cmd="COMMAND_DISCONNECT",
            signalPath=0,
            assertions=
            {
                {
                    path="graph.ports[0].numOutgoingConnections",
                    value=0,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
                {
                    path="graph.ports[2].numIncomingConnections",
                    value=0,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
                {
                    path="graph.numSignalPaths",
                    value=0,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
            },
        },
	}
}
    
