root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="Final",
			nodeName="final1",
			assertions=
			{
				{
					path="graph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="BarTyped",
			nodeName="bar1",
			assertions=
			{
				{
					path="graph.numNodes",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=2,
			toPort=1,
    			status=
			{
				statusCode="STATUS_SYNTAX_ERROR",
				resultType="RESULT_PORT",
			},
			assertions=
			{
				{
					path="graph.ports[2].direction",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.ports[2].numOutgoingConnections",
					value=0,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.ports[1].direction",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.ports[1].numIncomingConnections",
					value=0,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
                {
                    path="graph.numSignalPaths",
                    value=0,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
			},
		},
	}
}
