root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group1",
			assertions=
			{
				{
					path="graph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="FooTyped",
			nodeName="foo1",
			assertions=
			{
				{
					path="graph.numNodes",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=0,
			toPort=3,
			status=
			{
				statusCode="STATUS_OBJECT_NOT_FOUND",
				resultType="RESULT_PORT_ID",
			},
			assertions=
			{
				{
					path="graph.ports[0].numOutgoingConnections",
					value=0,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.ports[2].numIncomingConnections",
					value=0,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
                {
                    path="graph.numSignalPaths",
                    value=0,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
			},
		},
	}
}
    
