root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group1",
			assertions=
			{
				{
					path="graph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=0,
			toPort=1,
			status=
			{
				statusCode="STATUS_CYCLE_DETECTED",
				resultType="RESULT_NODE",
			},
			assertions=
			{
				{
					path="graph.ports[0].direction",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.ports[0].numOutgoingConnections",
					value=0,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.ports[1].direction",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.ports[1].numIncomingConnections",
					value=0,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
                {
                    path="graph.numSignalPaths",
                    value=0,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
			},
		},
	}
}
