root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=0,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="FooTyped",
			nodeName="foo1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=1,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="BarTyped",
			nodeName="bar1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=2,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=3,
			toPort=1,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
				signalPathID=0,
			},
			assertions=
			{
				{
					path="graph.ports[3].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.ports[1].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=0,
			toPort=2,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
				signalPathID=1,
			},
			assertions=
			{
				{
					path="graph.ports[0].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.ports[2].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_SELECT",
			selection=
			{
				0,
			},
			selectionMode="SELECTION_SET",
			assertions=
			{
				{
					path="numSelectedNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.numPorts",
					value=4,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{ 
					path="selection.inputs.size",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="selection.inputs[0].id",
					value=0,
					op="RELOP_EQ",
				},
				{
					path="selection.outputs.size",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="selection.outputs[0].id",
					value=0,
					op="RELOP_EQ",
				},
				{
					path="selection.internals.size",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="selection.internals[0].id",
					value=0,
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_CHILD",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=5,
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.nodes[1].class",
					value="FooTyped",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.nodes[2].class",
					value="BarTyped",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_SET_ACTIVE_GRAPH",
			graphPath=
			{
				0
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=6,
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=4,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="FooTyped",
			nodeName="foo1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=7,
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=5,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="BarTyped",
			nodeName="bar1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
 				nodeID=8,
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=6,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=8+3,
			toPort=8+1,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
				signalPathID=2,
			},
			assertions=
			{
				{
					path="activeGraph.ports[11].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[9].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=8+0,
			toPort=8+2,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
				signalPathID=3,
			},
			assertions=
			{
				{
					path="activeGraph.ports[8].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[10].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_SELECT",
			selection=
			{
				6,
			},
			selectionMode="SELECTION_SET",
			assertions=
			{
				{
					path="numSelectedNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.numPorts",
					value=10,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_CHILD",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=11,
			},
			assertions=
			{
                {
                    path="activeGraph.nodes[6].class",
                    value="GroupTyped",
                    op="RELOP_EQ",
                },
                {
                    path="activeGraph.nodes[7].class",
                    value="FooTyped",
                    op="RELOP_EQ",
                },
                {
                    path="activeGraph.nodes[8].class",
                    value="BarTyped",
                    op="RELOP_EQ",
                },
                {
                    path="activeGraph.children[0].nodes[9].class",
                    value="Boundary",
                    op="RELOP_EQ",
                },
                {
                    path="activeGraph.children[0].nodes[10].class",
                    value="Boundary",
                    op="RELOP_EQ",
                },
				{
					path="activeGraph.children[0].numNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
                {
                    path="activeGraph.numPorts",
                    value=8,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
				{
					path="activeGraph.children[0].numPorts",
					value=6,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[11].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].ports[8].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].ports[9].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].ports[12].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].ports[13].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].ports[14].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.children[0].ports[15].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.numNodes",
					value=6,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
	}
}
