root=
{
	items=
	{
		{
			cmd="COMMAND_DESERIALISE",
			filename="etc/tests/NodeEditorLive/CreateChildFanOut.txt",
			status=
			{
				statusCode="STATUS_OK",
			},
			existing=
			{
				{
					class="SignalPath",
					from=
					{
						parentClass="BarTyped",
					},
					to=
					{
						parentClass="Boundary",
					},
				},
				{
					class="SignalPath",
					from=
					{
						parentClass="Boundary",
					},
					to=
					{
						parentClass="FooTyped",
					},
					count=3,
				},
                {
                    path={0},
                    class="SignalPath",
                    from=
                    {
                        parentClass="Boundary",
                    },
                    to=
                    {
                        parentClass="GroupTyped",
                    },
                },
                {
                    path={0},
                    class="SignalPath",
                    from=
                    {
                        parentClass="GroupTyped",
                    },
                    to=
                    {
                        parentClass="Boundary",
                    },
                    count=3,
                },
			},
		},
	}
}
