root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="EnumTyped",
			nodeName="e1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=0,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
			existing=
			{
				{
					class="Port",
					properties=
					{
						parentClass="EnumTyped",
						value=
						{
							typeIndex="TYPE_VALUE",
							valueType="TYPE_ENUM",
							enumType="TestEnumWrapper",
							value="TEST_FOO",
						},
					},
				},
			},
		},
		{
			cmd="COMMAND_SET_PORT_VALUE",
			port=0,
			value=
			{
				typeIndex="TYPE_VALUE",
				valueType="TYPE_ENUM",
				enumType="TestEnumWrapper",
				value="TEST_BAR",
			},
			existing=
			{
				{
					class="Port",
					properties=
					{
						parentClass="EnumTyped",
						value=
						{
							typeIndex="TYPE_VALUE",
							valueType="TYPE_ENUM",
							enumType="TestEnumWrapper",
							value="TEST_BAR",
						},
					},
				},
			},
		},
	},
}
