root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=0,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="FooTyped",
			nodeName="foo1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=1,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="BarTyped",
			nodeName="bar1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=2,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=3,
			toPort=1,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
				signalPathID=0,
			},
            existing=
            {
                {
                    class="Port",
                    properties=
                    {
                        parentClass="BarTyped",
                        numOutgoingConnections=1,
                    },
                },
                {
                    class="Port",
                    properties=
                    {
                        parentClass="GroupTyped",
                        numIncomingConnections=1,
                    },
                },
                {
                    class="SignalPath",
                    from=
                    {
                        parentClass="BarTyped",                        
                    },
                    to=
                    {
                        parentClass="GroupTyped",
                    },
                },
            },
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=0,
			toPort=2,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
				signalPathID=1,
			},
            existing=
            {
                {
                    class="Port",
                    properties=
                    {
                        parentClass="GroupTyped",
                        numOutgoingConnections=1,
                    },
                },
                {
                    class="Port",
                    properties=
                    {
                        parentClass="FooTyped",
                        numIncomingConnections=1,
                    },
                },
                {
                    class="SignalPath",
                    from=
                    {
                        parentClass="GroupTyped",
                    },
                    to=
                    {
                        parentClass="FooTyped",
                    },
                },                
            },
		},
		{
			cmd="COMMAND_SELECT",
			selection=
			{
				0,
			},
			selectionMode="SELECTION_SET",
			assertions=
			{
				{
					path="numSelectedNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.numPorts",
					value=4,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_CHILD",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=5,
			},
            existing=
            {
                {
                    class="Node",
                    properties=
                    {
                        class="GraphNode",
                        totalPorts=2,
                    },
                },
                {
                    path={0},
                    class="Port",
                    properties=
                    {
                        sharedParentClass="GraphNode",
                        direction=1,
                        value=2.0,
                    },
                },
                {
                    path={0},
                    class="Port",
                    properties=
                    {
                        sharedParentClass="GraphNode",
                        direction=2,
                        value=1.0,
                    },
                },
                {
                    class="SignalPath",
                    from=
                    {
                        parentClass="BarTyped",
                    },
                    to=
                    {
                        parentClass="Boundary",
                    },
                },
                {
                    class="SignalPath",
                    from=
                    {
                        parentClass="Boundary",
                    },
                    to=
                    {
                        parentClass="FooTyped",
                    },
                },
                {
                    path={0},
                    class="SignalPath",
                    from=
                    {
                        parentClass="Boundary",
                    },
                    to=
                    {
                        parentClass="GroupTyped",
                    },
                },
                {
                    path={0},
                    class="SignalPath",
                    from=
                    {
                        parentClass="GroupTyped",
                    },
                    to=
                    {
                        parentClass="Boundary",
                    },
                },
                {
                    path={0},
                    class="Node",
                    properties=
                    {
                        class="GroupTyped",
                    },
                },
                {
                    class="Node",
                    properties=
                    {
                        class="FooTyped",
                    },
                },
                {
                    class="Node",
                    properties=
                    {
                        class="BarTyped",
                    },
                },
                {
                    path={0},
                    class="Node",
                    properties=
                    {
                        class="Boundary",
                        name="boundaryInput",
                    },
                },
                {
                    path={0},
                    class="Node",
                    properties=
                    {
                        class="Boundary",
                        name="boundaryOutput",
                    },
                },
                {
                    class="Port",
                    properties=
                    {
                        parentClass="BarTyped",
                        direction=2,
                        numOutgoingConnections=1,                
                    },
                },
                {
                    path={0},
                    class="Port",
                    properties=
                    {
                        parentClass="Boundary",
                        parentName="boundaryInput",
                        direction=1,
                        numIncomingConnections=1,                
                    },
                },
                {
                    class="Port",
                    properties=
                    {
                        parentClass="FooTyped",
                        direction=1,
                        numIncomingConnections=1,
                    },
                },
                {
                    path={0},
                    class="Port",
                    properties=
                    {
                        parentClass="Boundary",
                        parentName="boundaryOutput",
                        direction=2,
                        numOutgoingConnections=1,
                    },
                },
                {
                    path={0},
                    class="Port",
                    properties=
                    {
                        parentClass="GroupTyped",
                        direction=2,
                        numOutgoingConnections=1,
                    },
                },
                {
                    path={0},
                    class="Port",
                    properties=
                    {
                        parentClass="GroupTyped",
                        direction=1,
                        numIncomingConnections=1,
                    },
                },
                {
                    path={0},
                    class="Port",
                    properties=
                    {
                        parentClass="Boundary",
                        parentName="boundaryInput",
                        direction=2,
                        numOutgoingConnections=1,
                    },
                },
                {
                    path={0},
                    class="Port",
                    properties=
                    {
                        parentClass="Boundary",
                        parentName="boundaryOutput",
                        direction=1,
                        numIncomingConnections=1,
                    },
                },
                {
                    path={0},
                    class="Port",
                    properties=
                    {
                        parentClass="Boundary",
                        parentName="boundaryOutput",
                        direction=2,
                        numOutgoingConnections=1,
                    },
                },
            },
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.numSignalPaths",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].numSignalPaths",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.children[0].numNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
                {
                    path="graph.numPorts",
                    value=2,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
				{
					path="graph.children[0].numPorts",
					value=6,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
	}
}
