root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
 				nodeID=0,
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group2",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
 				nodeID=1,
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group3",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
 				nodeID=2,
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="FooTyped",
			nodeName="foo1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
 				nodeID=3,
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=4,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="BarTyped",
			nodeName="bar1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
 				nodeID=4,
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=5,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=0,
			toPort=3,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
 				signalPathID=0,
			},
			assertions=
			{
				{
					path="activeGraph.ports[0].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[3].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.numSignalPaths",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[0].fromPort",
					value=0,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[0].toPort",
					value=3,
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=2,
			toPort=5,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
 				signalPathID=1,
			},
			assertions=
			{
				{
					path="activeGraph.ports[2].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[5].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[1].fromPort",
					value=2,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[1].toPort",
					value=5,
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=4,
			toPort=6,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
 				signalPathID=2,
			},
			assertions=
			{
				{
					path="activeGraph.ports[4].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[6].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[2].fromPort",
					value=4,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[2].toPort",
					value=6,
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=7,
			toPort=1,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
 				signalPathID=3,
			},
			assertions=
			{
				{
					path="activeGraph.ports[7].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[1].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[3].fromPort",
					value=7,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[3].toPort",
					value=1,
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_SELECT",
			selection=
			{
				0,
				1,
				2,
			},
			selectionMode="SELECTION_SET",
			assertions=
			{
				{
					path="numSelectedNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.numPorts",
					value=8,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="selection.inputs.size",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="selection.inputs[0].id",
					value=0,
					op="RELOP_EQ",
				},
				{
					path="selection.outputs.size",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="selection.outputs[0].id",
					value=2,
					op="RELOP_EQ",
				},
				{
					path="selection.internals.size",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="selection.internals[0].id",
					value=0,
					op="RELOP_EQ",
				},
				{
					path="selection.internals[1].id",
					value=1,
					op="RELOP_EQ",
				},
				{
					path="selection.internals[2].id",
					value=2,
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_CHILD",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=7,
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[10].direction",
					value=1, -- IN
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[10].name",
					value="in1",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[10].parentClass",
					value="Boundary",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[8].direction",
					value=2, -- OUT
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[8].parentClass",
					value="Boundary",
					op="RELOP_EQ",
				},
				-- The shared Ports are in the child activeGraph
                {
                    path="activeGraph.numPorts",
                    value=2,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
				{
					path="activeGraph.children[0].signalPaths[0].fromPort",
					value=0,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].signalPaths[0].toPort",
					value=3,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].signalPaths[1].fromPort",
					value=2,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].signalPaths[1].toPort",
					value=5,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.nodes[7].class",
					value="GraphNode",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.nodes[7].totalPorts",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.nodes[7].dynamicPort[0].direction",
					value=1, -- IN
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.nodes[7].dynamicPort[1].direction",
					value=2, -- OUT
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.numSignalPaths",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[4].fromPort",
					value=8,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[4].toPort",
					value=1,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[5].fromPort",
					value=4,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[5].toPort",
					value=10,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].numSignalPaths",
					value=4,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[6].fromPort",
					value=7,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[6].toPort",
					value=9,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[7].fromPort",
					value=11,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.signalPaths[7].toPort",
					value=6,
					op="RELOP_EQ",
				},
                {
                    path="activeGraph.nodes[0].class",
                    value="GroupTyped",
                    op="RELOP_EQ",
                },
                {
                    path="activeGraph.nodes[1].class",
                    value="GroupTyped",
                    op="RELOP_EQ",
                },
                {
                    path="activeGraph.nodes[2].class",
                    value="GroupTyped",
                    op="RELOP_EQ",
                },
                {
                    path="activeGraph.nodes[3].class",
                    value="FooTyped",
                    op="RELOP_EQ",
                },
                {
                    path="activeGraph.nodes[4].class",
                    value="BarTyped",
                    op="RELOP_EQ",
                },
                {
                    path="activeGraph.children[0].nodes[5].class",
                    value="Boundary",
                    op="RELOP_EQ",
                },
                {
                    path="activeGraph.children[0].nodes[6].class",
                    value="Boundary",
                    op="RELOP_EQ",
                },
				{
					path="activeGraph.children[0].numNodes",
					value=5,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].numPorts",
					value=10,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[7].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[6].parentClass",
					value="FooTyped",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[6].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ"
				},
				{
					path="activeGraph.ports[1].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ"
				},
				{
					path="activeGraph.ports[7].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ"
				},
				{
					path="activeGraph.children[0].ports[0].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].ports[1].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].ports[4].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].ports[5].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].ports[10].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.children[0].ports[8].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
	}
}
    
