root=
{
	items=
	{
        {
            cmd="COMMAND_CREATE_NODE",
            nodeClass="GroupTyped",
            status=
            {
                statusCode="STATUS_OK",
                nodeID=0,
            },
            assertions=
            {
                {
                    path="graph.numNodes",
                    value=1,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
                {
					path="graph.numPorts",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
                },
            },
        },
        {
			cmd="COMMAND_DELETE_PORT",
			port=0,
			status=
			{
				statusCode="STATUS_OK",
			},
			assertions=
			{
				{
					path="graph.numPorts",
					value=1,
				},
			},
			existing=
			{
				{
					class="Node",
					properties=
					{
						totalPorts=1,
					},
				},
				{
					class="Port",
					properties=
					{
						name="in1",
						direction=1,
						flags=0,
						value=
						{
							typeIndex="TYPE_VALUE",
							value=2.0,
						},
					},
				},
			},
        },
	}
}
