root=
{
	items=
	{
		{
			cmd="COMMAND_DESERIALISE",
			filename="etc/tests/NodeEditorLive/ChildNode.txt",
			assertions=
			{
				{
					path="graph.numSignalPaths",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_SELECT",
			selection=
			{
				5,
			},
			selectionMode="SELECTION_SET",
			assertions=
			{
				{
					path="numSelectedNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_DELETE_NODE",
			node=5,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=5,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.numSignalPaths",
					value=0,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.numChildren",
					value=0,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_SERIALISE",
			filename="scratch/LoadConnectedDeleteGraphNodeThenSave.txt",
		},
	}
}
