root=
{
	cases=
	{
		{
			name="Loading a single Node with non-zero ID",
			subs=
			{
				{
					commandIndex=0,
					name="filename",
					value="etc/tests/Graph/onenodehybridports.lua",
				},
			},
			assertions=
			{
			},
		},
	},
	items=
	{
		{
			cmd="COMMAND_LOAD",
			filename="",
		},
		{
			cmd="COMMAND_SAVE",
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="BarTyped",
			nodeName="bar1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=2
			},
			assertions=
			{
				{
					path="activeGraph.nodes[1].class",
					value="Final",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.nodes[2].class",
					value="BarTyped",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[1].parentClass",
					value="Final",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[1].value",
					value=2.0,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[2].parentClass",
					value="Final",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[2].value",
					value=true,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[3].parentClass",
					value="Final",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[3].value",
					value=1,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[4].parentClass",
					value="BarTyped",
					op="RELOP_EQ",
				},
			},
		},
	},
}
