root=
{
	items=
	{
		{
			cmd="COMMAND_DESERIALISE",
			filename="etc/tests/NodeEditorLive/ChildNode.txt",
			assertions=
			{
				{
					path="graph.numNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.numPorts",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.numSignalPaths",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_DELETE_NODE",
			node=2,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=2,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
                {
                    path="graph.nodes[1].class",
                    value="FooTyped",                    
                },
				{
					path="graph.numPorts",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.numSignalPaths",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.numChildren",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_SERIALISE",
			filename="scratch/LoadConnectedDeleteSourceNodeThenSave.txt",
		},
	}
}
