root=
{
	cases=
	{
		{
			name="Loading a set of connected Nodes",
			subs=
			{
				{
					commandIndex=0,
					name="filename",
					value="etc/tests/Graph/connectednodesnonzeroid.lua",
				},
				{
					commandIndex=2,
					name="nodeClass",
					value="MathsNode",
				},
			},
			assertions=
			{
				{
					commandIndex=1,
					assertionIndex=0,
					value=2,
				},
				{
					commandIndex=2,
					assertionIndex=0,
					value=3,
				},
				{
					commandIndex=2,
					assertionIndex=1,
					value="MathsNode",
				},
				{
					commandIndex=2,
					assertionIndex=2,
					value="MathsNode",
				},
			},
		},
	},
	items=
	{
		{
			cmd="COMMAND_LOAD",
			filename="",
		},
		{
			cmd="COMMAND_SAVE",
			assertions=
			{
				{
					path="activeGraph.numNodes",
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.numSignalPaths",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=3,
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=0,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.nodes[3].class",
					value="",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[3].parentClass",
					value="",
					op="RELOP_EQ",
				},
			}
		},
	},
}
