root=
{
	items=
	{
		{
			cmd="COMMAND_DESERIALISE",
			filename="etc/tests/NodeEditorLive/ChildNode.txt",
		},
		{
			cmd="COMMAND_SELECT",
			selection=
			{
				5,
			},
			selectionMode="SELECTION_SET",
			assertions=
			{
				{
					path="numSelectedNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_TEMPLATE",
			nodeClass="Test",
			status=
			{
				statusCode="STATUS_OK",
			},
			assertions=
			{
				{
					path="nodeLib.classes.Test.id",
					value=9,
					op="RELOP_EQ",
				},
			}
		},
        {
            cmd="COMMAND_CREATE_NODE",
            nodeClass="Test",
            status=
            {
                statusCode="STATUS_OK",
                nodeID=6,
            },
            assertions=
            {
                {
                    path="graph.numNodes",
                    value=4,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
                {
					path="graph.numPorts",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
                },
            },
        },
        {
			cmd="COMMAND_CREATE_NODE",
			nodeClass="FooTyped",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=10,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=5,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
                {
					path="graph.numPorts",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
                },
			},
        },
        {
			cmd="COMMAND_CREATE_NODE",
			nodeClass="BarTyped",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=11,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=6,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
                {
					path="graph.numPorts",
					value=4,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
                },
			},
        },
        {
			cmd="COMMAND_CONNECT",
			fromPort=15,
			toPort=11,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
				signalPathID=8,
			},
			assertions=
			{
				{
					path="graph.numSignalPaths",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
        },
        {
			cmd="COMMAND_CONNECT",
			fromPort=15,
			toPort=11,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
				signalPathID=9,
			},
			assertions=
			{
				{
					path="graph.numSignalPaths",
					value=4,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
        },
		{
			cmd="COMMAND_SERIALISE",
			filename="scratch/LoadConnectedCreateTemplateThenSave.txt",
		},        
	}
}
