root=
{
	items=
	{
        {
			cmd="COMMAND_DESERIALISE",
			filename="etc/tests/NodeEditorLive/ChildNode.txt",
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
        },
		{
			cmd="COMMAND_SELECT",
			selection=
			{
				5,
			},
			selectionMode="SELECTION_SET",
			assertions=
			{
				{
					path="numSelectedNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_COPY_NODE",
			status=
			{
				statusCode="STATUS_OK",
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=6,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.numPorts",
					value=4,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			}
		},
		{
			cmd="COMMAND_SELECT",
			selection=
			{
				5,6
			},
			selectionMode="SELECTION_SET",
		},
		{
			cmd="COMMAND_COMPARE_NODES",
			comparisonFlags="CMP_NAME_BIT CMP_CONNECTIONS_COUNT_BIT",
			status=
			{
				statusCode="STATUS_OK",
			},
			assertions=
			{
			}
		},
	},
}
