root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=0,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_SET_POSITION",
			node=0,
			x=100.0,
			y=200.0,
			assertions=
			{
				{
					path="activeGraph.nodes[0].x",
					value=100.0,
					op="RELOP_EQ",
				},
				{
					path="activeGraph.nodes[0].y",
					value=200.0,
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_SELECT",
			selection=
			{
				0,
			},
			selectionMode="SELECTION_SET",
			assertions=
			{
				{
					path="numSelectedNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="graph.numPorts",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_CHILD",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=3,
			},
			assertions=
			{
			},
		},
		{
			cmd="COMMAND_SERIALISE",
			status=
			{
				statusCode="STATUS_OK",
			},
			assertions=
			{
				{
					path="activeGraph.children.size",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.nodes[3].graph.numNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
	}
}
