root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
 				nodeID=0,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group2",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
 				nodeID=1,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group3",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
 				nodeID=2,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="FooTyped",
			nodeName="foo1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
 				nodeID=3,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=4,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="BarTyped",
			nodeName="bar1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
 				nodeID=4,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=5,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=0,
			toPort=3,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
 				signalPathID=0,
			},
			assertions=
			{
				{
					path="activeGraph.ports[0].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[3].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=2,
			toPort=5,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
 				signalPathID=1,
			},
			assertions=
			{
				{
					path="activeGraph.ports[2].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[5].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=4,
			toPort=6,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
 				signalPathID=2,
			},
			assertions=
			{
				{
					path="activeGraph.ports[4].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[6].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=7,
			toPort=1,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
 				signalPathID=3,
			},
			assertions=
			{
				{
					path="activeGraph.ports[7].numOutgoingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.ports[1].numIncomingConnections",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_SELECT",
			selection=
			{
				0,
				1,
				2,
			},
			selectionMode="SELECTION_SET",
			assertions=
			{
				{
					path="numSelectedNodes",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="activeGraph.numPorts",
					value=8,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="selection.inputs.size",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="selection.inputs[0].id",
					value=0,
					op="RELOP_EQ",
				},
				{
					path="selection.outputs.size",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="selection.outputs[0].id",
					value=2,
					op="RELOP_EQ",
				},
				{
					path="selection.internals.size",
					value=3,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
				{
					path="selection.internals[0].id",
					value=0,
					op="RELOP_EQ",
				},
				{
					path="selection.internals[1].id",
					value=1,
					op="RELOP_EQ",
				},
				{
					path="selection.internals[2].id",
					value=2,
					op="RELOP_EQ",
				},
			},
		},
	}
}
    
