root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=0,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_SERIALISE",
            filename="scratch/SingleNode.txt",
            serialiseFormat="SERIALISE_FLAT",
			status=
			{
				statusCode="STATUS_OK",
			},
            existing=
            {
                {
                    class="Node",
                    properties=
                    {
                        class="GroupTyped",
                    },
                },
            },
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_DESERIALISE",
			filename="scratch/SingleNode.txt",
			serialiseFormat="SERIALISE_FLAT",
            existing=
            {
                {
                    class="Node",
                    properties=
                    {
                        class="GroupTyped",
                    },
                },
            },
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
	}
}
