root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=0,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="GroupTyped",
			nodeName="group1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=1,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=0,
			toPort=3,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
				signalPathID=0,
			},
            existing=
            {
                {
                    class="Port",
                    properties=
                    {
                        parentClass="GroupTyped",
                        numOutgoingConnections=1,
                    },
                },
                {
                    class="Port",
                    properties=
                    {
                        parentClass="GroupTyped",
                        numIncomingConnections=1,
                    },
                },
                {
                    class="SignalPath",
                    from=
                    {
                        parentClass="GroupTyped",
                    },
                    to=
                    {
                        parentClass="GroupTyped",
                    },
                },                
            },
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=2,
			toPort=1,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
				signalPathID=1,
			},
            existing=
            {
                {
                    class="Port",
                    properties=
                    {
                        parentClass="GroupTyped",
                        numOutgoingConnections=1,
                    },
                    count=2,
                },
                {
                    class="Port",
                    properties=
                    {
                        parentClass="GroupTyped",
                        numIncomingConnections=1,
                    },
                    count=2,
                },
                {
                    class="SignalPath",
                    from=
                    {
                        parentClass="GroupTyped",
                    },
                    to=
                    {
                        parentClass="GroupTyped",
                    },
                    count=2,
                },                
            },
		},
		{
			cmd="COMMAND_TOPO_SORT",
			status=
			{
				statusCode="STATUS_CYCLE_DETECTED",
			},
			order=
			{
			},
			cycle=
			{
				0,
				1,
				0,
			},
		},
	}
}
    
