root=
{
	items=
	{
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="BarTyped",
			nodeName="bar1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=0,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CREATE_NODE",
			nodeClass="FooTyped",
			nodeName="foo1",
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_NODE_ID",
				nodeID=1,
			},
			assertions=
			{
				{
					path="graph.numNodes",
					value=2,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
				},
			},
		},
		{
			cmd="COMMAND_CONNECT",
			fromPort=0,
			toPort=1,
			status=
			{
				statusCode="STATUS_OK",
				resultType="RESULT_SIGNAL_PATH_ID",
				signalPathID=0,
			},
			assertions=
			{
                {
                    path="graph.numSignalPaths",
                    value=1,
                    typeIndex="TYPE_UINT",
                    op="RELOP_EQ",
                },
			},
			existing=
			{
				{
					class="Port",
					properties=
					{
						numOutgoingConnections=1,
					},
				},
				{
					class="Port",
					properties=
					{
						numIncomingConnections=1,
					},
				},
				{
					class="SignalPath",
					from=
					{
						parentClass="BarTyped",
					},
					to=
					{
						parentClass="FooTyped",
					},
				},
			},
		},
        {
			cmd="COMMAND_SET_NODE_ACTIVE",
			node=1,
			commented="ACTIVE_OFF",
			existing=
			{
			},
			assertions=
			{
				{
					path="activeGraph.numNodes",
					value=1,
				},
                {
					path="graph.numPorts",
					value=1,
					typeIndex="TYPE_UINT",
					op="RELOP_EQ",
                },
			},
        },
		{
			cmd="COMMAND_TOPO_SORT",
			status=
			{
				statusCode="STATUS_OK",
			},
			order=
			{
				{0,1},
			},
		},
	}
}
