graph=
{
    nodes=
    {
        {
			id=1,
            name="foo1",
            class="FooTyped",
            category="CATEGORY_SINK",
            ports=
            {
                {
					id=1,
                    name="in1",
                    class="TypedPort<double>",
                    direction="DIR_IN",
                    type="TYPE_DOUBLE",
                    value=1.0,
                }
            }
        },
        {
			id=2,
            name="bar1",
            class="BarTyped",
            category="CATEGORY_SOURCE",
            ports=
            {
                {
					id=2,
                    name="out1",
                    class="TypedPort<double>",
                    direction="DIR_OUT",
                    type="TYPE_DOUBLE",
                    value=2.0,
                }
            }
        }
    },
    signalpaths=
    {
        {
			id=0,
            sourceNode=2,
            sourcePort=2,
            destNode=1,
            destPort=1
        },
    }
}
