graph=
{
    nodes=
    {
        {
            id=0,
            name="sine",
            class="MathsNode",
            category="CATEGORY_ACTION",
            ports=
            {
                {
					id=0,
                    name="angle",
                    class="TypedPort<double>",
                    direction="DIR_IN",
                    type="TYPE_DOUBLE",
                    value=0.0,                    
                },
                {
					id=1,
                    name="unit",
                    class="TypedPort<int64_t>",
                    direction="DIR_INTERNAL",
                    type="TYPE_INT64",
                    value=0,
                    metaPort=
                    {
                        allowedValues=
                        {
                            {0,"deg"},
                            {1,"rad"}
                        }
                    }
                },
                {
					id=2,
                    name="output",
                    class="TypedPort<double>",
                    direction="DIR_OUT",
                    type="TYPE_DOUBLE",
                    value=0.0,                    
                }
            }
        },
        {
            id=1,
            name="angle",
            class="BarTyped",
            category="CATEGORY_SOURCE",
            ports=
            {
                {
					id=3,
                    name="out1",
                    class="TypedPort<double>",
                    direction="DIR_OUT",
                    type="TYPE_DOUBLE",
                    value=math.pi/2.0,
                }
            }
        }
    },
    signalpaths=
    {
        {
			id=0,
            sourceNode=1,
            sourcePort=3,
            destNode=0,
            destPort=0,
        },
    }
}
