graph=
{
    nodes=
    {
        {
            id=0,
            class="NodePlugin.DynamicNode",
            name="node1",
            category="Group",
            numDynamicPortDescriptors=0,
            flags=0x0,
            ports=
            {
                {
                    name="port1",
                    class="TypedPort<double>",
                    type="TYPE_DOUBLE",
                    direction="DIR_OUT",
                    value=1.0,
                }
            },
        },
    },
    signalPaths=
    {
    },
    children=
    {
    }
}
