graph=
{
    nodes=
    {
        {
			id=1,
            name="final1",
            class="Final",
            category="Sink",
            ports=
            {
                {
					id=1,
					class="TypedPort<double>",
                    name="direction",
                    value=2.0
                },
                {
					id=2,
					class="TypedPort<bool>",
					name="trigger",
					value=true,
                },
                {
					id=3,
					class="TypedPort<int64_t>",
					name="int1",
					value=2,
                },
                {
					id=4,
					class="TypedPort<double>",
					name="hybrid1",
					type="TYPE_DOUBLE",
					value=5.0,
                },
            }
        }
    },
    signalpaths=
    {
    }
}
