graph=
{
    nodes=
    {
        {
            id=0,
            name="bound1",
            class="Boundary",
            category="Group",
            ports=
            {
                {
                    name="foo",
                    class="TypedPort<bool>",
                    direction="DIR_OUT",
                    type="TYPE_BOOL",
                    value=true
                },
                {
                    name="bar",
                    class="TypedPort<string>",
                    direction="DIR_OUT",
                    type="TYPE_STRING",
                    value="wibble"
                },
                {
                    name="baz",
                    class="TypedPort<int64_t>",
                    direction="DIR_OUT",
                    type="TYPE_INT",
                    value=1
                },
                {
                    name="qux",
                    class="TypedPort<double>",
                    direction="DIR_OUT",
                    type="TYPE_DOUBLE",
                    value=1.0
                }
            }
        }
    },
    signalpaths=
    {
    }
}
