graph=
{
    nodes=
    {
        {
			id=0,
            name="foo1",
            class="FooTyped",
            category="CATEGORY_SINK",
            ports=
            {
                {
					id=1,
                    name="in1",
                    class="TypedPort<double>",
                    direction="DIR_IN",
                    type="TYPE_DOUBLE",
                    value=2.0
                }
            }
        }
    },
    signalpaths=
    {
    },
	children=
	{
		{
			nodes=
			{
				{
					id=1,
					name="bar1",
					class="BarTyped",
					category="CATEGORY_SOURCE",
					ports=
					{
						{
							id=1,
							name="out1",
							class="TypedPort<double>",
							direction="DIR_OUT",
							type="TYPE_DOUBLE",
							value=3.0
						}
					}					
				}
			},
			children=
			{
				{
					nodes=
					{
						{
							id=2,
							name="bound1",
							class="Boundary",
							category="CATEGORY_GROUP",
							ports=
							{
								{
									id=2,
									name="in1",
									class="TypedPort<double>",
									direction="DIR_IN",
									type="TYPE_DOUBLE",
									value=2.0
								},
								{
									id=3,
									name="out1",
									class="TypedPort<double>",
									direction="DIR_OUT",
									type="TYPE_DOUBLE",
									value=3.0
								},
							}
						}
					}
				}
			}
		}
	}
}
